### ISSUE TITLE
[Feature] 建议添加 convert 相关功能

### ISSUE THREAD

**Issue by mumudm** [docer-savior/getter-setter-postfix-idea-plugin#17]
1. convert 方法能否不要在字段内生成注释，需要手动删除才行，增加下一步操作的麻烦
2. convert 能直接实体类.convert , 而不是写完一个 set 方法才能生成
3. convert 是否可以增加判空选项，为空直接返回 null

**Comment by gudqs7** [comment]
1.可以的
2.不太行(没有完整数据, 不太会使用idea的那种后输入信息的方式... 因为没看过相关的示例代码), 建议试另一种方式, 写一个方法, 返回值是 dest 对象, 入参是 src 对象, 声明写好后可在方法名上用 alt + enter 弹出选择 Generate Convert; 效果类似的, 此方式可配置 java8 stream 的 map 操作, `xx.stream().map(this::convertXxToXxx)`, 然后再 alt + enter 创建方法, 返回值 R 输入 dest 的类型即可.
3.好的

@mumudm 最近比较忙... 要过几天了

**Comment by gudqs7** [comment]
@mumudm 发现 2 似乎可以了

![image](https://user-images.githubusercontent.com/25474608/182517319-7faff7c8-75c0-4570-b805-f1a9625746e6.png)

**Comment by gudqs7** [comment]
@mumudm  v1.2.0 版本已发布, 已添加通过 dest 触发 convert
