### ISSUE TITLE
[BUG] 兄弟我导入完这个东西以后，我本地的postfix都变成2个了。怎么能联系到你

### ISSUE THREAD

**Issue by StackTc** [docer-savior/getter-setter-postfix-idea-plugin#7]

**Comment by gudqs7** [comment]
.......

**Comment by gudqs7** [comment]
你可以把微信号私发我邮箱.....  邮箱可以在提交记录找到

**Comment by gudqs7** [comment]
你给个截图看看, 如: 
![image](https://user-images.githubusercontent.com/25474608/173733232-f89bf504-9033-4919-857a-9bbbe1793977.png)

**Comment by gudqs7** [comment]
@StackTc

**Comment by gudqs7** [comment]
联系方式见 https://github.com/docer-savior
